import type { CardConfig } from '../CreditCard'

export const cubeConfigs: CardConfig[] = [
  {
    name: 'Cube 卡',
    description: '',
    cardUrl: null,
    storeBlackList: [],
    paymentBlackList: [],
    updateAt: '2024-12-01T00:00:00.000Z',
    airLines: 'EVA',
    plans: [
      {
        name: '集精選',
        rewards: [
          {
            reward: {
              type: 'RoundedPointsRewardPercentage',
              name: null,
              pointBackRate: 2,
              pointsPerMile: 300,
              milesPerUnit: 1000,
            },
            stores: ['台灣中油', '全聯', '7-11', '全家'],
            payments: [
              '信用卡',
              'Apple Pay',
              'Samsung Pay',
              'Google Pay',
              'Fitbit Pay',
              'Garmin Pay',
              'Hami Pay',
            ],
            transactionType: null,
          },
        ],
      },
      {
        name: '來支付',
        rewards: [
          {
            reward: {
              type: 'RoundedPointsRewardPercentage',
              name: null,
              pointBackRate: 2,
              pointsPerMile: 300,
              milesPerUnit: 1000,
            },
            stores: [],
            payments: ['Line Pay'],
            transactionType: null,
          },
        ],
      },
      {
        name: '玩數位',
        rewards: [
          {
            reward: {
              type: 'RoundedPointsRewardPercentage',
              name: null,
              pointBackRate: 3,
              pointsPerMile: 300,
              milesPerUnit: 1000,
            },
            stores: ['PChome', '蝦皮購物', '博客來', 'momo'],
            payments: [
              '信用卡',
              'Apple Pay',
              'Samsung Pay',
              'Google Pay',
              'Fitbit Pay',
              'Garmin Pay',
              'Hami Pay',
            ],
            transactionType: null,
          },
        ],
      },
      {
        name: '樂饗購',
        rewards: [
          {
            reward: {
              type: 'RoundedPointsRewardPercentage',
              name: null,
              pointBackRate: 3,
              pointsPerMile: 300,
              milesPerUnit: 1000,
            },
            stores: [
              'SOGO百貨',
              '太平洋百貨',
              '新光三越',
              'Uber Eats',
              'foodpanda',
              '康是美',
              '屈臣氏',
              '遠東SOGO百貨',
              '遠東Garden City',
              '太平洋百貨',
              '新光三越',
              'SKM Park',
              'BELLAVITA',
              '微風廣場',
              '遠東百貨',
              'Big City遠東巨城購物中心',
              '誠品生活 ',
              '環球購物中心',
              'CITYLINK',
              '統一時代',
              '台北101',
              'ATT 4 FUN',
              '明曜百貨',
              '京站',
              '美麗華',
              '大葉高島屋',
              '比漾廣場',
              '大江國際購物中心',
              '中友百貨',
              '廣三SOGO',
              'Tiger City',
              '勤美誠品綠園道',
              '大魯閣新時代',
              '耐斯廣場',
              '南紡購物中心',
              '夢時代',
              '漢神百貨',
              '漢神巨蛋',
              'MITSUI OUTLET PARK 林口',
              'MITSUI OUTLET PARK 台中港',
              'MITSUI OUTLET PARK 台南',
              'Mitsui Shopping Park LaLaport 台中',
              '義大世界購物廣場',
              '華泰名品城',
              '義享天地',
              '麗寶OUTLET Mall',
              '秀泰生活',
              '台茂購物中心',
              '新月廣場',
              '三創生活',
              '宏匯廣場',
              '高雄棧貳庫/大港倉',
              'NOKE忠泰樂生活',
            ],
            payments: [
              '信用卡',
              'Apple Pay',
              'Samsung Pay',
              'Google Pay',
              'Fitbit Pay',
              'Garmin Pay',
              'Hami Pay',
            ],
            transactionType: null,
          },
        ],
      },
      {
        name: '趣旅行',
        rewards: [
          {
            reward: {
              type: 'RoundedPointsRewardPercentage',
              name: null,
              pointBackRate: 3,
              pointsPerMile: 300,
              milesPerUnit: 1000,
            },
            stores: [
              '中華航空',
              '長榮航空',
              '星宇航空',
              '台灣虎航',
              '國泰航空',
              '樂桃航空',
              '阿聯酋航空',
              '酷航',
              '捷星航空',
              '日本航空',
              '亞洲航空',
              '聯合航空',
              'ANA全日空',
              '新加坡航空',
              '越捷航空',
              '大韓航空',
              '達美航空',
              '土耳其航空',
              '卡達航空',
              '法國航空',
            ],
            payments: [
              '信用卡',
              'Apple Pay',
              'Samsung Pay',
              'Google Pay',
              'Fitbit Pay',
              'Garmin Pay',
              'Hami Pay',
            ],
            transactionType: null,
          },
        ],
      },
    ],
  },
]
