import typia from 'typia'

export type StoreAliases = [string, string[]]
export const isStoreAliasesList = typia.createIs<StoreAliases[]>()

export const defaultStoreAliases: readonly [string, readonly string[]][] = [
  ['7-ELEVEN', ['7-11', 'Seven Eleven', '統一超商', '小7']],
  ['ANA全日空', ['ANA', '全日空', 'All Nippon Airways', 'NH']],
  ['ATT 4 FUN', ['ATT4FUN', 'ATT信義']],
  ['App Store', ['蘋果應用商店']],
  ['Apple Arcade', ['蘋果遊戲訂閱服務']],
  ['Apple Music', ['蘋果音樂', 'Apple音樂']],
  ['Apple One', ['蘋果One訂閱']],
  ['Apple TV+', ['Apple TV Plus']],
  ['Apple Wallet ICOCA', ['ICOCA電子票', 'Apple錢包ICOCA']],
  ['Apple Wallet PASMO', ['PASMO電子票', 'Apple錢包PASMO']],
  ['Apple Wallet SUICA', ['SUICA電子票', 'Apple錢包SUICA']],
  ['CITYLINK', ['City Link']],
  ['Disney+', ['Disney Plus', '迪士尼+']],
  ['Google Play', ['Google應用商店']],
  ['Grab', ['Grab Taxi', 'Grab叫車']],
  ['MITSUI OUTLET PARK 台中港', ['三井台中港', '三井OUTLET台中']],
  ['MITSUI OUTLET PARK 台南', ['三井台南', '三井OUTLET台南']],
  ['MITSUI OUTLET PARK 林口', ['三井林口', '三井OUTLET林口']],
  ['Mitsui Shopping Park LaLaport 台中', ['LaLaport台中', '三井LaLaport台中']],
  ['Netflix', ['網飛']],
  ['Nintendo', ['任天堂', 'Switch', '老任']],
  ['PChome 24h購物(不含儲值及電子票券)', ['PChome', 'PChome購物']],
  ['Tiger City', ['老虎城', 'Tiger City購物中心']],
  ['Trip.com', ['攜程']],
  ['Uber Eats (不含 Uber One)', ['優步外送']],
  ['foodpanda', ['熊貓外送', 'Food Panda']],
  ['iCloud', ['蘋果雲端', 'iCloud雲端']],
  ['iRent', ['i Rent']],
  ['iTunes', ['蘋果iTunes']],
  ['中友百貨', ['中友']],
  ['中華航空', ['China Airlines', 'CAL', 'CI', '華航']],
  ['亞洲航空', ['AirAsia', '亞航', 'AXM', 'AK']],
  ['京站', ['Q Square', '京站商場']],
  ['全家便利商店', ['FamilyMart', '全家']],
  ['全球迪士尼飯店', ['Disney Hotels']],
  ['全聯福利中心', ['PX Mart']],
  ['南紡購物中心', ['Tainan Spinnery Mall', '南紡']],
  ['博客來', ['Books.com.tw']],
  ['卡達航空', ['Qatar Airways', '卡航', 'QTR', 'QR']],
  ['可樂旅遊', ['Cola Travel', '可樂旅行社']],
  ['台北101', ['Taipei 101', '101大樓']],
  ['台灣中油-直營', ['中油直營', '直營中油']],
  ['台灣大車隊', ['Taiwan Taxi', '大車隊']],
  ['台灣虎航', ['Tigerair Taiwan', '台虎', 'TWA', 'IT']],
  ['台灣高鐵', ['Taiwan High Speed Rail']],
  ['台茂購物中心', ['TaiMall']],
  ['吉卜力公園', ['Ghibli Park']],
  ['國泰航空', ['Cathay Pacific', '國泰', 'CPA', 'CX', 'Cathay Pacific Airways']],
  ['土耳其航空', ['Turkish Airlines', '土航', 'THY', 'TK']],
  ['夢時代', ['Dream Mall']],
  ['大阪環球影城(USJ)', ['Universal Studios Japan']],
  ['大韓航空', ['Korean Air', '韓航', 'KAL', 'KE']],
  ['大魯閣新時代', ['Taroko Mall', '大魯閣']],
  ['太平洋百貨', ['Pacific Department Store', '太平洋']],
  ['好樂迪KTV', ['Holiday']],
  ['家樂福', ['Carrefour']],
  ['屈臣氏', ['Watsons']],
  ['康是美', ['Cosmed']],
  ['捷星航空', ['JST', 'JQ', 'Jetstar Airways']],
  ['新加坡航空', ['SIA', 'SQ', 'Singapore Airlines']],
  ['日本航空', ['JAL', 'JL', 'Japan Airlines']],
  ['星宇航空', ['starlux', 'SJX', 'JX', 'STARLUX Airlines']],
  ['樂桃航空', ['APJ', 'MM', 'Peach Aviation']],
  ['法國航空', ['AFR', 'AF', 'Air France']],
  ['聯合航空', ['UAL', 'UA', 'United Airlines']],
  ['蝦皮購物', ['shopee']],
  ['越捷航空', ['VJC', 'VJ', 'VietJet Air']],
  ['達美航空', ['DAL', 'DL', 'Delta Air Lines']],
  ['遠東百貨', ['遠百']],
  ['酷航', ['SCO', 'TR', 'Scoot']],
  ['長榮航空', ['EVA', 'BR', 'EVA Airlines', 'EVA Air']],
  ['阿聯酋航空', ['UAE', 'EK', 'Emirates']],
  ['麥當勞', ["McDonald's"]],
  ['IKEA', ['宜家家居']],
  ['星巴克', ['starbucks']],
] satisfies StoreAliases[]
